version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
  flaskapp:
    build: "."
    ports:
    - "5432:5432"
    depends_on:
      - "db"